config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: %i[create new]
  resources :registrations, only: %i[create new]
  get "/logout", to: "sessions#destroy", as: :logout
  resources :posts, only: %i[create new index edit update show]
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[edit update show]
  before_action :authenticate_user, only: %i[new create edit update]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params.merge(user_id: session[:user_id])

    if @post.valid?
      @post.save
      redirect_to root_path, notice: "Post created!"
    else
      redirect_to new_post_path,
                  status: :unprocessable_entity,
                  alert: @post.errors.full_messages.join(", ")
    end
  end

  def edit
  end

  def update
    redirect_to root_path unless @post.user_id == session[:user_id]

    if @post.update post_params
      redirect_to root_path, notice: "Post updated!"
    else
      redirect_to edit_post_path(@post),
                  status: :unprocessable_entity,
                  alert: @post.errors.full_messages.join(", ")
    end
  end

  def show
    @post = Post.find params[:id]
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def set_post
    @post = Post.find params[:id]
  end

  def authenticate_user
    redirect_to root_path unless session[:user_id]
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new params[:user].permit(:email, :password)
    if user.save
      session[:user_id] = user.id
      redirect_to root_path, notice: "Thanks for signing up!"
    else
      redirect_to new_registration_path,
                  alert: user.errors.full_messages.join(", ")
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # user = User.new email: params[:email], password: params[:password]
    user = User.find_by email: params[:email]

    if user&.password == params[:password]
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in successfully"
    else
      redirect_to new_session_path,
                  status: :unprocessable_entity,
                  alert: "Invalid email or password"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out successfully"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p style="color: green;">
      <%= notice %>
    </p>
    <p style="color: red;">
      <%= alert %>
    </p>
    <% if session[:user_id] %>
      Logged in as <strong><%= User.find(session[:user_id]).email %></strong>.
      <%= link_to "Logout", logout_path %>
    <% else %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<div style="border: 1px grey solid; padding: 8px; margin: 8px;">
  <h1>
    <%= post.title %>
  </h1>

  <p>
    <%= post.body %>
  </p>

  <br>
  by <strong><%= post.user.email %></strong>

  <% if session[:user_id] == post.user.id %>
    <%= link_to 'Edit', edit_post_path(post) %>
  <% end %>
  <%= link_to 'Show', post_path(post) %>
<div>

app/views/posts/edit.html.erb
<h1>Post edition</h1>

<%= form_for @post do |f|%>
  <%= f.text_field :title, placeholder: 'Title', autofocus: true %>
  <br>
  <%= f.text_area :body, placeholder: 'Body' %>
  <br>
  <%= f.submit 'Update' %>
<% end %>

app/views/posts/index.html.erb
<h1>
  Posts
</h1>

<% if session[:user_id] %>
  <%= link_to 'New post', new_post_path %>
<% end %>
<br>

<ul>
  <% @posts.each do |post|%>
    <li>
      <%= render post %>
    </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= form_for @post do |f|%>
  <%= f.text_field :title, placeholder: 'Title', autofocus: true %>
  <br>
  <%= f.text_area :body, placeholder: 'Body' %>
  <br>
  <%= f.submit 'Publish' %>
<% end %>

app/views/posts/show.html.erb
<h1>
  <%= @post.title %>
</h1>

<p>
  <%= @post.body %>
</p>

<br>
by <strong><%= @post.user.email %></strong>

<% if session[:user_id] == @post.user.id %>
  <%= link_to 'Edit', edit_post_path(@post) %>
<% end %>